---
mysql_root_password: "your_secure_password"
mysql_db_name: "wordpress_db"
mysql_db_user: "wordpress_user"
mysql_db_password: "another_secure_password"

domain: "yourdomain.com"
wordpress_admin_user: "admin"
wordpress_admin_password: "wp_admin_password"
wordpress_admin_email: "admin@yourdomain.com"
wordpress_title: "My WordPress Site"
wordpress_locale: "en_US"  # Change to "fa_IR" for Persian, etc.
wordpress_db_prefix: "wp_"

ssl_email: "your@email.com"
php_version: "8.3"
linux_username: "ubuntu"  # Your server user