- hosts: all  
  become: true  

  tasks:  
    - name: Configure Nginx  
      template:  
        src: templates/nginx.conf.j2  
        dest: "/etc/nginx/sites-available/{{ domain }}"  
      notify: Restart Nginx  

    - name: Ensure sites-available directory exists
      ansible.builtin.file:
        path: /etc/nginx/sites-available
        state: directory
        mode: '0755'
      become: true

    - name: Ensure sites-enabled directory exists
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled
        state: directory
        mode: '0755'
      become: true

    - name: Configure Nginx for WordPress
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ domain }}
        mode: '0644'
      become: true

    - name: Enable Nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ domain }}
        dest: /etc/nginx/sites-enabled/{{ domain }}
        state: link
        force: yes
      become: true
      notify: Restart Nginx


    - name: Add user to www-data group  
      user:  
        name: "{{ linux_username }}"  
        groups: www-data  
        append: yes  

    - name: Create site directory  
      file:  
        path: "/var/www/{{ domain }}/html"  
        state: directory  
        mode: '0775'  
        owner: www-data  
        group: www-data  

    - name: Create site logs directory  
      file:  
        path: "/var/www/{{ domain }}/logs"  
        state: directory  
        mode: '0775'  
        owner: www-data  
        group: www-data  

    - name: Create cache directory  
      file:  
        path: "/etc/nginx/cache/{{ domain }}"  
        state: directory  
        mode: '0755'  
        owner: www-data  
        group: www-data  

    - name: Download WordPress core  
      shell: wp core download --locale='{{ wordpress_locale }}'  
      args:  
        chdir: "/var/www/{{ domain }}/html"  
      become_user: "{{ linux_username }}"  

    - name: Create wp-config.php  
      shell: wp config create --dbname={{ mysql_db_name }} --dbuser={{ mysql_db_user }} --dbpass='{{ mysql_db_password }}' --dbprefix={{ wordpress_db_prefix }} --locale={{ wordpress_locale }}  
      args:  
        chdir: "/var/www/{{ domain }}/html"  
      become_user: "{{ linux_username }}"  

    - name: Install WordPress
      ansible.builtin.shell: sudo -u www-data wp core install --url='http://{{ domain }}' --title='{{ wordpress_title }}' --admin_user='{{ wordpress_admin_user }}' --admin_password='{{ wordpress_admin_password }}' --admin_email='{{ wordpress_admin_email }}'
      args:
        chdir: /var/www/{{ domain }}/html
      become: true 

    - name: Set correct permissions for directories  
      file:  
        path: "/var/www/{{ domain }}/html"  
        state: directory  
        recurse: yes  
        mode: '0775'  
        owner: www-data  
        group: www-data  

    - name: Find all WordPress files  
      find:  
        paths: "/var/www/{{ domain }}/html"  
        file_type: file  
        recurse: yes  
      register: wp_files  




  handlers:
  - name: Restart Nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
    become: true