# 15-generate-docs.yml
- hosts: localhost
  connection: local # Ensure connection is local
  gather_facts: false # Usually not needed for local doc generation
  vars:
    # These global variables would ideally be defined in a global scope like group_vars/all.yml
    # or passed as extra-vars if this playbook is run standalone.
    effective_enable_multilingual_docs: "{{ GLOBAL_ENABLE_MULTILINGUAL_DOCS | default(false) }}"
    effective_doc_languages: "{{ GLOBAL_DOC_LANGUAGES_LIST | default(['en', 'fa']) }}" # Example default

  # This entire playbook should only run if multilingual doc generation is enabled.
  when: effective_enable_multilingual_docs | bool

  tasks:
    - name: "Placeholder: Generate multilingual READMEs for project documentation"
      ansible.builtin.debug:
        msg: "Attempting to generate documentation for languages: {{ effective_doc_languages | join(', ') }}. Actual generation script/tool needs to be implemented here."
      tags: ['docs', 'project_utils']
      # Example of what a real task might look like (conceptual):
      # - name: "Run documentation generation script for {{ item }} language"
      #   ansible.builtin.command: "scripts/generate_readme.sh {{ item }}"
      #   loop: "{{ effective_doc_languages }}"
      #   args:
      #     chdir: "{{ playbook_dir }}/.." # Assuming script is in project root's scripts folder
      #   changed_when: false # Or based on script output