# فایل جدید: 23-install-fail2ban.yml
---
- hosts: all
  become: true
  tasks:
    - name: Install Fail2ban
      apt:
        name: fail2ban
        state: present
        update_cache: yes
      when: domain_config.fail2ban_enabled | default(false)

    - name: Create Fail2ban WordPress filter
      copy:
        dest: /etc/fail2ban/filter.d/wordpress.conf
        content: |
          [Definition]
          failregex = ^%(__prefix_line)s.*POST /wp-login.php.*$ from <HOST>
          ignoreregex =
        owner: root
        group: root
        mode: '0644'
      when: domain_config.fail2ban_enabled | default(false)
      notify: Restart Fail2ban

    - name: Create Fail2ban WordPress jail
      copy:
        dest: /etc/fail2ban/jail.d/wordpress.conf
        content: |
          [wordpress]
          enabled = true
          port = http,https
          filter = wordpress
          logpath = /var/www/{{ domain_config.domain }}/logs/access.log
          maxretry = {{ domain_config.fail2ban_maxretry | default(3) }}
          findtime = {{ domain_config.fail2ban_findtime | default('10m') }}
          bantime = {{ domain_config.fail2ban_bantime | default('24h') }}
        owner: root
        group: root
        mode: '0644'
      when: domain_config.fail2ban_enabled | default(false)
      notify: Restart Fail2ban

    - name: Create Fail2ban SSH jail
      copy:
        dest: /etc/fail2ban/jail.d/sshd.conf
        content: |
          [sshd]
          enabled = true
          port = ssh
          filter = sshd
          logpath = /var/log/auth.log
          maxretry = {{ domain_config.fail2ban_maxretry | default(3) }}
          findtime = {{ domain_config.fail2ban_findtime | default('10m') }}
          bantime = {{ domain_config.fail2ban_bantime | default('24h') }}
        owner: root
        group: root
        mode: '0644'
      when: domain_config.fail2ban_enabled | default(false)
      notify: Restart Fail2ban

  handlers:
    - name: Restart Fail2ban
      service:
        name: fail2ban
        state: restarted
      when: domain_config.fail2ban_enabled | default(false)
