# File: 24-secure-file-permissions.yml
# Author: Sayyed Jamal Ghasemi
# Full Stack Developer
# Email: jamal13647850@gmail.com
# LinkedIn: https://www.linkedin.com/in/jamal1364/
# Instagram: https://www.instagram.com/jamal13647850
# Telegram: https://t.me/jamaldev
# Website: https://jamalghasemi.com
# Date: 2024-06-20

- hosts: all
  become: true
  vars:
    # Variables remain unchanged as per user request
    effective_secure_file_permissions: "{{ domain_config.secure_file_permissions | default(GLOBAL_SECURE_FILE_PERMISSIONS_POLICY | default(true)) }}"
    _app_domain: "{{ domain_config.domain }}"
    _app_webroot: "/var/www/{{ _app_domain }}/html"
    _wp_config_path: "/var/www/{{ _app_domain }}/wp-config.php"  # Path to WordPress configuration file
    _web_user: "{{ domain_config.linux_username | default(GLOBAL_LINUX_USERNAME | default('www-data')) }}"
    _web_group: "{{ domain_config.linux_group | default(GLOBAL_LINUX_GROUP | default('www-data')) }}"

  tasks:
    # Find all directories inside the webroot
    - name: "Find all directories inside the webroot"
      ansible.builtin.find:
        paths: "{{ _app_webroot }}"
        file_type: directory
      register: found_dirs
      tags: ['permissions', 'filesystem', 'hardening']

    # Set permissions 755 for directories
    - name: "Set secure permissions for directories (755)"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
      loop: "{{ found_dirs.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      tags: ['permissions', 'filesystem', 'hardening']

    # Find all files inside the webroot
    - name: "Find all files inside the webroot"
      ansible.builtin.find:
        paths: "{{ _app_webroot }}"
        file_type: file
      register: found_files
      tags: ['permissions', 'filesystem', 'hardening']

    # Set permissions 644 for files
    - name: "Set secure permissions for files (644)"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: file
        mode: '0644'
      loop: "{{ found_files.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
      tags: ['permissions', 'filesystem', 'hardening']
    
    # Set the most secure permissions for wp-config.php file (600)
    - name: "Set the MOST secure permissions for wp-config.php (0600)"
      ansible.builtin.file:
        path: "{{ _wp_config_path }}"
        mode: '0600'  # Improved from 0640 to 0600 for maximum security
        owner: "{{ _web_user }}"
        group: "{{ _web_group }}"
      when: domain_config.platform == "wordpress"
      tags: ['permissions', 'wordpress', 'hardening', 'wp-config']

    # Set ownership recursively for webroot files and directories
    - name: "Set proper ownership for all files and directories"
      ansible.builtin.file:
        path: "{{ _app_webroot }}"
        owner: "{{ _web_user }}"
        group: "{{ _web_group }}"
        recurse: yes
      tags: ['permissions', 'filesystem', 'ownership']

    # Disable file editing from WordPress admin dashboard in wp-config.php
    - name: "Disable direct file editing in wp-config.php"
      ansible.builtin.lineinfile:
        path: "{{ _wp_config_path }}"
        line: "define('DISALLOW_FILE_EDIT', true);"
        regexp: "^\\s*define\\s*\\(\\s*'DISALLOW_FILE_EDIT'\\s*,"
        insertbefore: "^\\/\\*\\s*That's all, stop editing! Happy publishing\\.\\s*\\*\\/"
        state: present
      when: domain_config.platform == "wordpress"
      tags: ['permissions', 'wordpress', 'hardening', 'wp-config']
