---
# laravel/04-laravel-queue.yml
- hosts: all
  become: true
  tasks:
    - name: Create Laravel queue worker systemd service
      template:
        src: templates/laravel-worker.service.j2
        dest: "/etc/systemd/system/laravel-worker-{{ domain_config.domain | replace('.', '-') }}.service"
        mode: '0644'
      when: domain_config.enable_queue | default(false) | bool
    
    - name: Reload systemd
      systemd:
        daemon_reload: yes
      when: domain_config.enable_queue | default(false) | bool
    
    - name: Enable and start Laravel queue worker
      systemd:
        name: "laravel-worker-{{ domain_config.domain | replace('.', '-') }}"
        state: started
        enabled: yes
      when: domain_config.enable_queue | default(false) | bool
