- hosts: wordpress
  become: true
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Deploy for each domain
      include_tasks: "{{ item.playbook }}"
      loop:
        - { playbook: "00-update-upgrade.yml" }
        - { playbook: "01-install-mysql.yml" }
        - { playbook: "02-install-nginx.yml" }
        - { playbook: "03-install-php-composer-wpcli.yml" }
        - { playbook: "04-install-wordpress.yml" }
        - { playbook: "05-obtain-ssl.yml" }
        - { playbook: "06-install-redis.yml", when: "domains[domain].install_redis | default(false)" }
      loop_control:
        loop_var: item
      with_dict: "{{ domains }}"
      vars:
        domain: "{{ item.key }}"
        domain_config: "{{ item.value }}"